name: Bicep Deploy

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - uses: azure/CLI@v1
      with:
        inlineScript: |
           az deployment sub create \
             --location ${{ env.LOCATION}} \
             --parameters bicep/main.dev.bicepparam
